#!/usr/bin/env ruby

mode = ARGV[0]
key = ARGV[1]

if mode.nil? || ['help', 'h'].include?(mode)
  puts "USAGE:"
  puts "remote press <key> <times>"
  puts "remote hold <key> <seconds>"
  exit
end

if mode == 'press'
  count = ARGV[2].nil? ? 10 : ARGV[2]
  system("irsend --count #{count} SEND_ONCE xr11 #{key}")
else
  seconds = ARGV[2].nil? ? 2 : ARGV[2]
  system("irsend SEND_START xr11 #{key}")
  sleep seconds.to_f
  system("irsend SEND_STOP xr11 #{key}")
end
