#!/usr/bin/env ruby

mode = ARGV[0]
key = ARGV[1]
remote_name = ARGV[2]

if mode.nil? || ['help', 'h'].include?(mode)
  puts "USAGE:"
  puts "remote press <key> <remote_name> <times>"
  puts "remote hold <key> <remote_name> <seconds>"
  exit
end

if mode == 'press'
  count = ARGV[3].nil? ? 10 : ARGV[3].to_i
  system("irsend --count #{count} SEND_ONCE #{remote_name} #{key}")
else
  seconds = ARGV[3].nil? ? 2 : ARGV[3]
  system("irsend SEND_START #{remote_name} #{key}")
  sleep seconds.to_f
  system("irsend SEND_STOP #{remote_name} #{key}")
end
